language: perl
# v0.019_000
perl:
# NEED ANSWER, CORRELATION #rp000: is RPerl truly incompatible with Perl v5.8 and earlier?
# Perl v5.8 causes $CPP_LINKED global symbol errors, currently disabled
#    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    # version(s) below are built using Travis-CI Helper
    - "5.25" 
#    - "dev"  # same as 5.25 above
    - "blead"

# DEV NOTE, CORRELATION #rp011: update g++ to 4.8 for full C++11 support, including:
# -std=c++11, std::string::pop_back(), etc.

# new Docker container-based Travis-CI stack, currently disabled, does not support update-alternatives
#addons:
#    apt:
#       sources:
#           - ubuntu-toolchain-r-test
#addons:
#    apt:
#       packages:
#           - g++-4.8
#           - time


# [ BEGIN Travis-CI Helper ]
matrix:
    allow_failures:
        - perl: "5.25"
        - perl: "blead"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V

# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
#    - build-dist
#    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
# [ END Travis-CI Helper ]

    # legacy Travis-CI stack, currently enabled, supports sudo & update-alternatives
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo apt-get install libgmp-dev
    # begin Pluto PolyCC
    - sudo apt-get install texinfo
    #- wget https://github.com/wbraswell/pluto-mirror/raw/master/backup/pluto-0.11.4.tar.gz  # prefer official Pluto repo below
    - wget https://github.com/bondhugula/pluto/files/737550/pluto-0.11.4.tar.gz
    - tar -xzvf pluto-0.11.4.tar.gz
    - cd pluto-0.11.4/
    - ./configure
    - make
    - make test
    - sudo make install
    - cd ..
    # end Pluto PolyCC
    - sudo apt-get install curl
    #- sudo apt-get install astyle  # rely on Alien::astyle for more platform-independent testing

# NEED REMOVE FOLLOWING 1 LINE IF NOT USED
# NEED REMOVE FOLLOWING 1 LINE IF NOT USED
# NEED REMOVE FOLLOWING 1 LINE IF NOT USED
    #- cpan-install --deps       # Travis-CI Helper: installs prereqs, including recommends

before_script:
    # NEED REMOVE FOLLOWING 1 LINE when bug is fixed   https://github.com/daoswald/Inline-CPP/issues/38
    - cpanm --verbose --force ExtUtils::CppGuess
# MODIFY FOLLOWING LINE TO ENABLE TEST_VERBOSE STDOUT DURING `make test`
    - export RPERL_VERBOSE=0
# UNCOMMENT FOLLOWING LINE TO ENABLE NOISY BUILD DURING `make test`; REQUIRES RPERL_VERBOSE=1 ABOVE
#    - export RPERL_DEBUG=1
# UNCOMMENT FOLLOWING LINE FOR DEV VERSIONS OF MODULES, which travis can't get from Makefile.PL
#    - cpanm -n INGY/Inline-C-0.62_03.tar.gz
# DEV NOTE: Alien::base v0.036 requires Test2::Suite which seems to be causing RPerl builds to error
#    - cpanm --verbose Test2::Suite  # FAIL, TAKES FOREVER
#    - cpanm -n Test2::Suite  # PASS, SKIP TESTS
#    - wget https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test2-Suite-0.000067.tar.gz && tar -xzf Test2-Suite-0.000067.tar.gz && cd Test2-Suite-0.000067 && cpanm --verbose --installdeps . && perl Makefile.PL && make && make test TEST_VERBOSE=1 && make install && cd ..  # FAIL, MANUAL BUILD
#    - wget https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test2-Suite-0.000068-TRIAL.tar.gz && tar -xzf Test2-Suite-0.000068-TRIAL.tar.gz && cd Test2-Suite-0.000068* && cpanm --verbose --installdeps . && perl Makefile.PL && make && make test TEST_VERBOSE=1 && make install && cd ..  # PASS, TRIAL FIX
# DEV NOTE, CORRELATION #rp011: following line was not necessary until before_install & install sections added
#    - cpanm --quiet --installdeps --notest .
    - cpanm --verbose --installdeps .

# replace default build command "perl Makefile.PL && make test"
# DEV NOTE: TEST_VERBOSE variable for ExtUtils::MakeMaker 'make' command disables suppression of stdout;
# this variable is different than, and inherits the value of, the $RPERL_VERBOSE environmental variable 
script: perl Makefile.PL && make test TEST_VERBOSE=$RPERL_VERBOSE

notifications:
    irc:
        channels:
            - "irc.perl.org#perl11"
        on_success: always
        on_failure: always
        # to enable skip_join, in IRC channel first execute `/mode -n`
        skip_join: true
        template:
            - "RPerl build %{result}. %{author} says '%{commit_message}'"
            - "%{build_url} %{compare_url}"

env:
    global:
        - AUTHOR_TESTING=0
