language: perl
# v0.041_000
perl:
# NEED ANSWER, CORRELATION #rp000: is RPerl truly incompatible with Perl v5.8 and earlier?
# Perl v5.8 causes $CPP_LINKED global symbol errors, currently disabled
#    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
    - "blead"  # built using Travis-CI Helper

# DEV NOTE, CORRELATION #rp011: update g++ to 4.8 for full C++11 support, including:
# -std=c++11, std::string::pop_back(), etc.

# new Docker container-based Travis-CI stack, currently disabled, does not support update-alternatives
#addons:
#    apt:
#       sources:
#           - ubuntu-toolchain-r-test
#addons:
#    apt:
#       packages:
#           - g++-4.8
#           - time


# [ BEGIN Travis-CI Helper ]
matrix:
    allow_failures:
        # NEED FIX, CORRELATION #aj100: in Alien::JPCRE2, why is File::Find::Rule from t/02_make_check.t failing in v5.25 and v5.27 only?!?
        - perl: "blead"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V

# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
# NEED REMOVE FOLLOWING 2 LINES IF NOT USED
#    - build-dist
#    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
# [ END Travis-CI Helper ]

    # legacy Travis-CI stack, currently enabled, supports sudo & update-alternatives
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install gcc-5 g++-5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90 --slave /usr/bin/g++ g++ /usr/bin/g++-5
#   - sudo apt-get install libpcre2-8-0 libpcre2-16-0 libpcre2-32-0 libpcre2-dev  # DEV NOTE, CORRELATION #rp060: disabled, does not exist until Ubuntu v16.04 Xenial
#   - sudo apt-get install libjpcre2-dev                                          # DEV NOTE, CORRELATION #rp060: disabled, does not exist
    - perl -e 'if ($ENV{ALIEN_INSTALL_TYPE} eq q{system}) { system qw(sudo apt-get install astyle); }'       # "system" install via Ubuntu  here vs "share" install via CPAN Alien::astyle
    - perl -e 'if ($ENV{ALIEN_INSTALL_TYPE} eq q{system}) { system qw(sudo apt-get install libgmp-dev); }'   # "system" install via Ubuntu  here vs "share" install via CPAN Alien::GMP
    - perl -e 'if ($ENV{ALIEN_INSTALL_TYPE} eq q{system}) { system qw(sudo apt-get install libgsl0-dev); }'  # "system" install via Ubuntu  here vs "share" install via CPAN Alien::GSL
    - perl -e 'if ($ENV{ALIEN_INSTALL_TYPE} eq q{system}) { system qw(sudo apt-get install texinfo); }'      # "system" install via Ubuntu  here vs "share" install via CPAN Alien::Texinfo (A::Pluto dep)
    - perl -e 'if ($ENV{ALIEN_INSTALL_TYPE} eq q{system}) { system q{wget https://github.com/bondhugula/pluto/files/737550/pluto-0.11.4.tar.gz; tar -xzvf pluto-0.11.4.tar.gz; cd pluto-0.11.4/; ./configure; make; make test; sudo make install; cd .. }; }'  # "system" install via tarball here vs "share" install via CPAN Alien::Pluto

before_script:
    # DEV NOTE, CORRELATION #rp060: must force share install of dists which are not available via system install; PCRE2 & JPCRE2 are not readily available via the OS package manager
    # Configuring Alien-PCRE2-xxx ... Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
    # Alien::Build::CommandSequence> + pkg-config --exists libpcreX-X
    # external command failed at xxx/Alien/Build/CommandSequence.pm line XX.
    # N/A
    # ! Configure failed for Alien-PCRE2-xxx
    - ALIEN_INSTALL_TYPE=share && cpanm --verbose Alien::PCRE2 && cpanm --verbose Alien::JPCRE2
    # NEED REMOVE FOLLOWING 1 LINE when bug is fixed   https://github.com/daoswald/Inline-CPP/issues/38
    - cpanm --verbose --force ExtUtils::CppGuess
# MODIFY FOLLOWING LINE TO ENABLE TEST_VERBOSE STDOUT DURING `make test`
    - export RPERL_VERBOSE=0
# UNCOMMENT FOLLOWING LINE TO ENABLE NOISY BUILD DURING `make test`; REQUIRES RPERL_VERBOSE=1 ABOVE
#    - export RPERL_DEBUG=1
# UNCOMMENT FOLLOWING LINE FOR DEV VERSIONS OF MODULES, which travis can't get from Makefile.PL
#    - cpanm -n INGY/Inline-C-0.62_03.tar.gz
# DEV NOTE, CORRELATION #rp011: following line was not necessary until before_install & install sections added
#    - cpanm --quiet --installdeps --notest .
# DEV NOTE: after adding multiple Alien dependencies with build times, we exceeded Travis' ~40-minute time limit, disable CPAN tests for now to shorten non-RPerl build times
#    - cpanm --verbose --installdeps .



# DEV NOTE: verbose install to debug specific CPAN failures
# NEED DISABLE, TMP DEBUG
# NEED DISABLE, TMP DEBUG
# NEED DISABLE, TMP DEBUG
#    - export ALIEN_GSL_REPO_FTP_PROTOCOL=http
    - cpanm --verbose Alien::GSL

# DEV NOTE: after adding multiple Alien dependencies with build times, we exceeded Travis' ~4MB log data limit, disable verbose CPAN output for now to shorten non-RPerl log output
    - cpanm --installdeps --notest .



# replace default build command "perl Makefile.PL && make test"
# DEV NOTE: TEST_VERBOSE variable for ExtUtils::MakeMaker 'make' command disables suppression of stdout;
# this variable is different than, and inherits the value of, the $RPERL_VERBOSE environmental variable 
script: perl Makefile.PL && make test TEST_VERBOSE=$RPERL_VERBOSE

notifications:
    irc:
        channels:
            - "irc.perl.org#perl11"
        on_success: always
        on_failure: always
        # to enable skip_join, in IRC channel first execute `/mode -n`
        skip_join: true
        template:
            - "RPerl build %{result}. %{author} says '%{commit_message}'"
            - "%{build_url} %{compare_url}"

env:
    global:
        - AUTHOR_TESTING=0
    matrix:
#        - ALIEN_INSTALL_TYPE=share
        - ALIEN_INSTALL_TYPE=system
